id: I84191088
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:10:02+00:00'
last_modified: '2022-06-08T05:53:32.713838+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159408
  title: མཚོ་སྣ་བ་སྟོབས་རྒྱལ་གྱི་དཔྱད་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    1E15:
      image_group_id: I2PD18973
      title: ''
      total_pages: 728
      order: 1
      base_file: 1E15.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
